import {test,expect} from '@playwright/test';
test('создание квиза → гость → ответ → результат → лидерборд → финал',async({page,browser})=>{
 await page.goto('/admin');await page.getByLabel('Пароль ведущего').fill('test-only-party-password');await page.getByRole('button',{name:'Войти в студию'}).click();await page.getByRole('button',{name:'Создать квиз',exact:true}).click();
 await page.getByLabel('Название квиза').fill('Вечеринка Playwright');await page.getByLabel('Текст вопроса').fill('Сколько будет два плюс два?');await page.getByLabel('Вариант 1',{exact:true}).fill('Четыре');await page.getByLabel('Вариант 2',{exact:true}).fill('Пять');await expect(page.getByText('Все изменения сохранены')).toBeVisible();
 await page.screenshot({path:'work/editor.png',fullPage:true});await page.getByRole('button',{name:'Начать игру',exact:true}).click();await expect(page).toHaveURL(/\/host\//);const code=await page.locator('.game-code').innerText();const sid=page.url().split('/').pop()!;
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const guest=await context.newPage();await guest.goto('/play?code='+code.trim());await guest.getByLabel('Как вас представить?').fill('Лиза');await guest.getByRole('button',{name:'Присоединиться'}).click();await expect(guest.getByText('ВЫ В СПИСКЕ ГОСТЕЙ')).toBeVisible();
 const screen=await browser.newPage({viewport:{width:1920,height:1080}});await screen.goto('/screen/'+sid);await expect(screen.locator('.game-code')).toContainText(code);await screen.screenshot({path:'work/projector.png',fullPage:true});
 await page.getByRole('button',{name:'Начать игру',exact:true}).click();await page.getByRole('button',{name:'Первый вопрос',exact:true}).click();await expect(guest.getByRole('button',{name:/Четыре/})).toBeVisible();await guest.screenshot({path:'work/phone.png',fullPage:true});await guest.getByRole('button',{name:/Четыре/}).click();await guest.getByRole('button',{name:'Это мой ответ'}).click();await expect(guest.getByText('Ответ принят!',{exact:true})).toBeVisible();await guest.reload();await expect(guest.getByText('Ответ принят!',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Закрыть ответы',exact:true}).click();await page.getByRole('button',{name:'Показать ответ',exact:true}).click();await expect(guest.getByText('Вот это ответ!')).toBeVisible();await page.getByRole('button',{name:'Итоги раунда',exact:true}).click();await expect(screen.getByRole('heading',{name:'Кто впереди?'})).toBeVisible();await expect(guest.locator('.own-rank')).toContainText('#1');await page.getByRole('button',{name:'Показать финал',exact:true}).click();await expect(screen.getByRole('heading',{name:'Ваши аплодисменты!'})).toBeVisible();await screen.screenshot({path:'work/final.png',fullPage:true});
 const download=page.waitForEvent('download');await page.getByRole('link',{name:'Скачать XLSX'}).click();expect((await download).suggestedFilename()).toBe('party-results.xlsx');await context.close();await screen.close();
});
